#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=30        \
                 blur_radius=30   \
                 position=top     \
                 sticky=on        \
                 floating=on      \
                 y_offset=5       \
                 padding_left=0   \
                 padding_right=0  \
                 margin=5         \
                 corner_radius=20 \
                 color=$TRANSPARENT

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.color=$TRANSPARENT       \
                     background.corner_radius=10            \
                     background.height=20                  \
                     padding_left=5                       \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=5                \
                     icon.padding_left=5                  \
                     icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh

# -- Brackets --
sketchybar --add bracket left_group front_app '/space\..*/' \
           --set left_group background.color=$BAR_COLOR \
                            background.corner_radius=15 \
                            background.height=30 \
                            background.padding_left=10 \
                            background.padding_right=10

sketchybar --add bracket right_group media calendar wifi volume battery cpu memory  \
           --set right_group background.color=$BAR_COLOR \
                             background.corner_radius=15 \
                             background.height=30 \
                             background.padding_left=10 \
                             background.padding_right=10

# Apply individual backgrounds to items in the right_group
sketchybar --set media    background.color=$ITEM_BG_COLOR \
           --set calendar background.color=$ITEM_BG_COLOR \
           --set volume   background.color=$ITEM_BG_COLOR \
           --set battery  background.color=$ITEM_BG_COLOR \
           --set cpu      background.color=$ITEM_BG_COLOR \
           --set memory   background.color=$ITEM_BG_COLOR \
           --set wifi     background.color=$ITEM_BG_COLOR

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update